name1 = input("what is your name ")
friend1 = input("what is your friends name ")
hobby1 = input("what is your favorite hobby ")
food1 = input("what is your favorite food ")
print(" one day your friend " + friend1 + " was "+hobby1+ " after " +friend1+ " invited " +name1+ " out for " + food1 +" the end ")
input= ("press  ENTER to exit")